### ISSUE TITLE
Facebook not displaying text

### ISSUE THREAD

**Issue by Adriano72** [ricardoalcocer/socialshare#11]
Dear Ricardo,

thanks for this great piece of code.

I have a problem with it: if I chose Facebook it doesn't add any text in the Facebook sharing text area, but it nevertheless work perfectly with email sharing, google+, whatsapp etc. 

This problems shows in both iOS and Android. Both the devices I used are upgraded the latest versions of iOS and Android OS.

What can I do to fix it? It looks as a Facebook only issue

Thanks!
Best
Adriano

**Comment by gabrielperales** [comment]
I'm having the same issue, but seems like the issue is not about this library, otherwise is about TiSocial.Framework https://github.com/viezel/TiSocial.Framework/issues/136 . I'll see what can we do :-).

**Comment by gabrielperales** [comment]
As I have readed here http://stackoverflow.com/questions/29881531/ios-8-3-and-later-facebook-share-text-not-inserted the issue is about the facebook app. It is not longer allowing to share text. You can only share urls.

**Comment by andersdp** [comment]
On Android (don't know about iOS) when initiatiating the share sheet I send both the url and an image. Which is great for sharing through everything else but facebook. Facebook shares the image without the url - if I only send the url to the share sheet facebook works like I want it to (I have added open graph meta info on the url) but the other services like Messages and e-mail only get an url which users don't quite understand.

So: Would it possible to work around this? Send both url and image, but facebook only gets the url?

**Comment by mawarnes** [comment]
Hi when I share via Facebook with image and url, only the url is being shared. Is this intended behaviour?
