### ISSUE TITLE
Whatsapp share error

### ISSUE THREAD

**Issue by PietroGranati** [ricardoalcocer/socialshare#12]
Since last update from whatsapp this text no work anymore.
var shareMe = require('com.alcoapps.socialshare');
    shareMe.share({
        status              : "download  www.1live.it/app.php",
        androidDialogTitle  : 'Segnala tramite:',
        view                : $.Rcondividi
    });

**Comment by ricardoalcocer** [comment]
You should ask about this [here](https://github.com/viezel/TiSocial.Framework/issues).
