### ISSUE TITLE
Share PDF

### ISSUE THREAD

**Issue by arildojr** [ricardoalcocer/socialshare#17]
Hi,

Does it share PDF files?
If not do you know any other module for that?

Thanks

**Comment by ricardoalcocer** [comment]
I haven't used this in a while :( , but by looking at it and trying to remember, it was intended to share images or text.

However, see here: https://github.com/ricardoalcocer/socialshare/blob/master/app/widgets/com.alcoapps.socialshare/lib/com.alcoapps.socialshare.js#L34

I suppose you can add a check for the content type and send the appropriate one to the intent - this is on Android.  

For iOS I believe you can use the Ti.UI.iOS.createDocumentViewer, unless the TiSocial.Framework (a dependency) already supports it.

Sorry I can't be more helpful.
