### ISSUE TITLE
How to control share by email?

### ISSUE THREAD

**Issue by daveeel** [ricardoalcocer/socialshare#3]
In Ti, we could use createEmailDialog to control email subject and messageBody.
Anyway to do the same with socialshare? There's no use of 'status' in the sample usage. The email is just empty. How to set email subject & body?

Thanks.

**Comment by ricardoalcocer** [comment]
This is something that could be added, at least for Android.  Will have to see how [TiSocial.Framework](https://github.com/viezel/TiSocial.Framework) handles this.
