### ISSUE TITLE
Android intent callback info

### ISSUE THREAD

**Issue by andersdp** [ricardoalcocer/socialshare#4]
Would it be possible to add something like the iOS Social.addEventListener("complete", function(e){});?

**Comment by andersdp** [comment]
Doing this:
`var chooser = Ti.Android.createIntentChooser(intent, args.androidDialogTitle);
Ti.Android.currentActivity.startActivityForResult(chooser, function(e)
{
     console.log(JSON.stringify(e));
});`

I get this output:
`{
"resultCode": 0,
    "source": {
        "actionBar": {
            "title": null,
            "bubbleParent": true,
            "apiName": "Ti.Android.ActionBar",
            "subtitle": null,
            "navigationMode": 0
        },
        "apiName": "Ti.Android.Activity",
        "bubbleParent": true
    },
    "intent": null,
    "requestCode": 1
}`

But nothing about the service the user shared via. I want to do some stats on how my users share.

Perhaps it's not possible to get this information at all?

**Comment by andersdp** [comment]
Anyone has some input?

**Comment by jabele** [comment]
Were you ever able to find an answer to this?

**Comment by andersdp** [comment]
No. Unfortunately not.

**Comment by jabele** [comment]
I was able to solve it by:

    var sharingSheetOpen = false;		
    mapview.addEventListener('click', function(evt) {
        if (evt.clicksource == 'rightPane' && !sharingSheetOpen){
            sharingSheetOpen = true;
            //// SEND INTENT INFORMATION HERE
        } else if (evt.clicksource == 'pin'){
            sharingSheetOpen = false;
            //// NOW THAT THE PIN HAS BEEN CLICKED AGAIN YOU CAN ACCEPT CLICKS
        };
    });`

**Comment by andersdp** [comment]
@jabele But that will not tell us which service the user shared with?

**Comment by jabele** [comment]
Correct. This just prevents the sharing sheet from opening multiple times. No callback information is provided that I can find.
