### ISSUE TITLE
dk.napp.social module wont support in 3.4.1 and above????

### ISSUE THREAD

**Issue by KusumaScriptbees** [ricardoalcocer/socialshare#5]
was trying social share module but i use 3.5.0 GA of Titanium Version it is not supporting. Will Support or Not??? Please let me know.

i had used below tags in tiapp.xml but still no luck

    <modules>
    <module platform="iphone">dk.napp.social</module> 
    </modules>

**Comment by KusumaScriptbees** [comment]
hey i'm sorry i had added the modules folder inside app folder so it was not able recognize the module now it is working fine.Thank you so much for the module...:)

**Comment by jabele** [comment]
I saw that you were trying to get this to work for 3.5.0 GA.  How did you end up getting this to work in that version?
