### ISSUE TITLE
Facebook does not appear, Twitter and other apps does

### ISSUE THREAD

**Issue by amurovsky** [ricardoalcocer/socialshare#6]
Facebook doesn´t appear in the Activity other apps like twitter, pinterest, whatssapp does,

and Social.isFacebookSupported() method of the social.framework module returns true.

I guess it's a conflict with the new SDK of Facebook.

**Comment by e3bmo3ty** [comment]
how you solve this, facebook shows up but no text shows

**Comment by almsx** [comment]
@e3bmo3ty It was not a practical solution but the client I sold the idea to add a picture to accompany the text, for marketing strategies. But now I have a problem I can not assign a default status using Facebook. This using 3.5.1.GA

**Comment by ricardoalcocer** [comment]
Remember that this module relies on Ti.SocialFramework and I'm basically wrapping its features.  Any specific question about it's features should be asked at https://github.com/viezel/TiSocial.Framework.

About the Facebook issue, on iOS the user needs to have the Facebook account added to the Phone (in Settings).  Ti.SocialFramework checks there to see if Facebook is available.
