### ISSUE TITLE
Facebook Post Image without Status in Device

### ISSUE THREAD

**Issue by almsx** [ricardoalcocer/socialshare#7]
Problem Detected: 
In iPhone 5S (8.3) and using Titanium SDK 3.5.1.GA when installing the application and want to share content using socialWidget only allows posting the attached image, but not the text of Status to post on Facebook; While using the same code but using the iPhone Simulator 5, 5S, 6 and if possible publish 6plus image and text status.

Source code employee

function shareImageWidget() {
			var img = 'img/gm.png';
			var socialWidget = Alloy.createWidget('com.alcoapps.socialshare');
			socialWidget.share({
				status : 'Hola Mexico!',
				image : img
			});
};

Attachment Device and simulator screens

![ios simulator screen shot 23 05 2015 10 31 37](https://cloud.githubusercontent.com/assets/361558/7784760/f2bbde04-0136-11e5-955d-47e87fbc9e14.png)

![img_0319 2](https://cloud.githubusercontent.com/assets/361558/7784767/23af3f56-0137-11e5-89de-e37335d403ae.PNG)

**Comment by ricardoalcocer** [comment]
This module is a wrapper around Ti.SocialFramework on iOS.  Any question about this behavior should be directed to the author of that module at https://github.com/viezel/TiSocial.Framework
