### ISSUE TITLE
Whatsapp sharing

### ISSUE THREAD

**Issue by MariaSanchez** [ricardoalcocer/socialshare#9]
Hello,

I am using this module for my apps and it is great, the only problem I have is when I try to share an image through Whatsapp on iOS, no image appears on the message. Is there any known issue, or is there anything I am missing? This is my code:

            var social = require('/lib/com.alcoapps.socialshare');

	    social.share({
			status : 'Status text',
			image : (Path to my image),
	    });

**Comment by artanisdesign** [comment]
Whatsapp wont pick up the image, i think it has nothing to do with this lib nor the other module. It's just how whatsapp works currently.
